# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-27 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yandex_money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('shop_id', models.PositiveIntegerField(default=27877, verbose_name='ID \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u0430')),
                ('scid', models.PositiveIntegerField(default=14748, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0432\u0438\u0442\u0440\u0438\u043d\u044b')),
                ('customer_number', models.CharField(default=yandex_money.models.uuid_generator, max_length=64, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a\u0430')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('article_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('payment_type', models.CharField(choices=[(b'pc', '\u042f\u043d\u0434\u0435\u043a\u0441.\u0414\u0435\u043d\u044c\u0433\u0438'), (b'ac', '\u0411\u0430\u043d\u043a\u043e\u0432\u0441\u043a\u0430\u044f \u043a\u0430\u0440\u0442\u0430'), (b'gp', '\u041f\u043e \u043a\u043e\u0434\u0443 \u0447\u0435\u0440\u0435\u0437 \u0442\u0435\u0440\u043c\u0438\u043d\u0430\u043b'), (b'mc', '\u0421\u043e \u0441\u0447\u0435\u0442\u0430 \u043c\u043e\u0431\u0438\u043b\u044c\u043d\u043e\u0433\u043e \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'), (b'wm', 'WebMoney'), (b'sb', '\u0412\u044b\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0441\u0447\u0435\u0442\u0430 \u0432 \u0421\u0431\u0435\u0440\u0431\u0430\u043d\u043a.\u041e\u043d\u043b\u0430\u0439\u043d'), (b'ab', '\u0412\u044b\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0441\u0447\u0435\u0442\u0430 \u0432 \u0410\u043b\u044c\u0444\u0430\u041a\u043b\u0438\u043a')], default=b'pc', max_length=2, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043f\u043b\u0430\u0442\u0435\u0436\u0430')),
                ('order_number', models.CharField(default=yandex_money.models.uuid_generator, max_length=64, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('cps_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email \u043f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a\u0430')),
                ('cps_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u043f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a\u0430')),
                ('success_url', models.URLField(default=b'https://www.kudanamore.ru/account/payments/success-payment/', verbose_name='URL \u0443\u0441\u043f\u0435\u0448\u043d\u043e\u0439 \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('fail_url', models.URLField(default=b'https://www.kudanamore.ru/account/payments/fail-payment/', verbose_name='URL \u043d\u0435\u0443\u0441\u043f\u0435\u0448\u043d\u043e\u0439 \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('status', models.CharField(choices=[(b'processed', b'Processed'), (b'success', b'Success'), (b'fail', b'Fail')], default=b'processed', max_length=16, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('invoice_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438 \u043e\u043f\u0435\u0440\u0430\u0442\u043e\u0440\u0430')),
                ('shop_amount', models.DecimalField(blank=True, decimal_places=2, help_text='\u0417\u0430 \u0432\u044b\u0447\u0435\u0442\u043e\u043c \u043f\u0440\u043e\u0446\u0435\u043d\u0442\u0430 \u043e\u043f\u0435\u0440\u0430\u0442\u043e\u0440\u0430', max_digits=15, null=True, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u043d\u0430\u044f \u043d\u0430 \u0440/\u0441')),
                ('order_currency', models.PositiveIntegerField(choices=[(643, '\u0420\u0443\u0431\u043b\u0438'), (10643, '\u0422\u0435\u0441\u0442\u043e\u0432\u0430\u044f \u0432\u0430\u043b\u044e\u0442\u0430')], default=643, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430')),
                ('shop_currency', models.PositiveIntegerField(blank=True, choices=[(643, '\u0420\u0443\u0431\u043b\u0438'), (10643, '\u0422\u0435\u0441\u0442\u043e\u0432\u0430\u044f \u0432\u0430\u043b\u044e\u0442\u0430')], default=643, null=True, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u043d\u0430\u044f \u043d\u0430 \u0440/\u0441')),
                ('performed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u0437\u0430\u043f\u0440\u043e\u0441\u0430')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ('-pub_date',),
                'verbose_name': '\u043f\u043b\u0430\u0442\u0451\u0436',
                'verbose_name_plural': '\u043f\u043b\u0430\u0442\u0435\u0436\u0438',
            },
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set([('shop_id', 'order_number')]),
        ),
    ]
