# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ym_merchant_receipt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
