# Generated by Django 2.2.9 on 2019-12-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_money', '0002_payment_ym_merchant_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fail_url',
            field=models.URLField(default='', verbose_name='URL неуспешной оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('pc', 'Яндекс.Деньги'), ('ac', 'Банковская карта'), ('gp', 'По коду через терминал'), ('mc', 'Со счета мобильного телефона'), ('wm', 'WebMoney'), ('sb', 'Выставление счета в Сбербанк.Онлайн'), ('ab', 'Выставление счета в АльфаКлик')], default='pc', max_length=2, verbose_name='Способ платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='scid',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер витрины'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shop_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID магазина'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('success', 'Success'), ('fail', 'Fail')], default='processed', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='success_url',
            field=models.URLField(default='', verbose_name='URL успешной оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
